apiVersion: v1
kind: Service
metadata:
  name: drkko-client-svc
spec:
  selector:
    app: drkko-client
  ports:
    - name: http
      protocol: TCP
      port: 3500
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drkko-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drkko-client
  template:
    metadata:
      labels:
        app: drkko-client
    spec:
      containers:
        - name: drkko-client
          image: dreamkakao/musicq-client:ff9d3496d0193d39be30f3cea13e371becd3d7db
