apiVersion: v1
kind: Service
metadata:
  name: drkko-client-svc
spec:
  selector:
    app: drkko-client
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drkko-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drkko-client
  template:
    metadata:
      labels:
        app: drkko-client
    spec:
      containers:
        - name: drkko-client
          image: dreamkakao/musicq-client:e0bf436cbe4d7101f91974f7cab5b173930c7f6b
