apiVersion: v1
kind: Service
metadata:
  name: drkko-service-svc
spec:
  selector:
    app: drkko-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drkko-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drkko-service
  template:
    metadata:
      labels:
        app: drkko-service
    spec:
      containers:
        - name: drkko-service
          image: dreamkakao/musicq-service:ea1e3d97b520c637ab8a06977e71263fd251c1e9
