apiVersion: v1
kind: Service
metadata:
  name: drkko-client-svc
spec:
  selector:
    app: drkko-client
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drkko-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drkko-client
  template:
    metadata:
      labels:
        app: drkko-client
    spec:
      containers:
        - name: drkko-client
          image: dreamkakao/musicq-client:9be94f94aea25731c1601968a4df42a6a4047ae6
